//! flint — Easy-to-hack agent harness in Rust.

mod cli;
mod config_ui;
mod display;
mod input;
mod markdown;
mod model_ui;
mod prompt;
mod provider;
mod repl;
mod resume_ui;
pub mod session_import;
mod setup_ui;
mod tools;

use anyhow::Result;
use clap::Parser;
use cli::{AgentArgs, Cli, Commands, SetupArgs};
use flint_agent::{Session, ToolContext, ToolRegistry};
use flint_config::Feature;
use flint_mcp::McpManager;
use flint_provider::Provider;
use std::sync::atomic::{AtomicBool, Ordering};
use std::sync::{Arc, Mutex};

// ── Subcommand handlers ───────────────────────────────────────────────────

fn cmd_config(working_dir: &std::path::Path) -> Result<()> {
    let config = flint_config::load(Some(working_dir))?;
    let save_path = config.save_path(Some(working_dir));
    config_ui::run(config, &save_path)?;
    Ok(())
}

fn cmd_setup(args: SetupArgs, working_dir: &std::path::Path) -> Result<()> {
    let env_path = provider::resolve_env_path(working_dir);

    if let (Some(provider), Some(key)) = (&args.provider, &args.key) {
        return setup_auto(&env_path, provider, key, args.base_url.as_deref(), args.model.as_deref());
    }

    let configured = setup_ui::run(&env_path)?;
    if configured {
        print_post_setup_guidance(&env_path);
    }
    Ok(())
}

fn setup_auto(
    env_path: &std::path::Path,
    provider: &str,
    api_key: &str,
    base_url: Option<&str>,
    model: Option<&str>,
) -> Result<()> {
    let p = setup_ui::find_provider(provider).ok_or_else(|| {
        anyhow::anyhow!("unknown provider '{}'. Supported: openai, anthropic", provider)
    })?;

    let mut lines = vec![
        "# flint configuration -- generated by `flint setup`".to_string(),
        format!("FLINT_PROVIDER={}", p.name),
        format!("{}={}", p.env_key, api_key),
    ];

    if let Some(url) = base_url {
        lines.push(format!("{}={}", p.env_base, url));
    }
    if let Some(m) = model {
        lines.push(format!("{}={}", p.env_model, m));
    }

    let content = if env_path.exists() {
        let existing = std::fs::read_to_string(env_path)?;
        let filtered: String = existing
            .lines()
            .filter(|line| {
                !line.starts_with(&format!("{}=", p.env_key))
                    && !line.starts_with(&format!("{}=", p.env_base))
                    && !line.starts_with(&format!("{}=", p.env_model))
                    && !line.starts_with("FLINT_PROVIDER=")
                    && !line.starts_with("FLINT_MODEL=")
            })
            .collect::<Vec<_>>()
            .join("\n");
        format!("{}\n{}\n", filtered.trim_end(), lines.join("\n"))
    } else {
        format!("{}\n", lines.join("\n"))
    };

    std::fs::write(env_path, &content)?;

    println!("+ Provider configured:");
    println!("  Provider : {}", p.label);
    println!(
        "  API Key  : {}...{}",
        &api_key[..4.min(api_key.len())],
        &api_key[api_key.len().saturating_sub(4)..]
    );
    if let Some(url) = base_url {
        println!("  Base URL : {}", url);
    }
    if let Some(m) = model {
        println!("  Model    : {}", m);
    }
    println!("  Saved to : {}", env_path.display());
    print_post_setup_guidance(env_path);
    Ok(())
}

fn print_post_setup_guidance(env_path: &std::path::Path) {
    println!();
    println!("Next steps:");
    println!("  - Run `flint` to start the interactive REPL");
    println!("  - Run `flint \"your prompt\"` for a one-shot query");
    println!("  - Run `flint config` to adjust features and settings");
    println!("  - Edit {} to change credentials", env_path.display());
    println!();
}

// ── Agent command ─────────────────────────────────────────────────────────

async fn cmd_agent(args: AgentArgs, working_dir: &std::path::Path) -> Result<()> {
    // Load .env: global -> project -> cwd
    let global_env = provider::home_dir().map(|h| h.join(".flint").join(".env"));
    let project_env = working_dir.join(".env");
    let cwd_env = std::env::current_dir().ok().map(|d| d.join(".env"));

    if let Some(ref path) = global_env {
        if path.exists() {
            provider::load_env_override(path);
        }
    }
    if project_env.exists() {
        provider::load_env_override(&project_env);
    }
    if let Some(ref path) = cwd_env {
        if path.exists() && path.as_path() != project_env.as_path() {
            provider::load_env_override(path);
        }
    }

    let env_path = provider::resolve_env_path(working_dir);
    let mut config = flint_config::load(Some(working_dir))?;

    // Resolve provider: CLI > env > config
    let env_provider = std::env::var("FLINT_PROVIDER").ok();
    let env_model = std::env::var("FLINT_MODEL").ok();

    let provider_type = args
        .provider
        .clone()
        .or_else(|| env_provider.clone())
        .unwrap_or_else(|| config.provider.r#type.clone());
    let model = args
        .model
        .clone()
        .or_else(|| env_model.clone())
        .unwrap_or_else(|| config.provider.model.clone());

    // Build provider; on failure, launch setup wizard
    let raw_prov: Box<dyn Provider> = match provider::build_provider(&provider_type, &model) {
        Ok(p) => p,
        Err(e) => {
            eprintln!("{}\n", e);
            eprintln!("Launching setup wizard...\n");
            let configured = setup_ui::run(&env_path)?;
            if !configured {
                eprintln!("Setup cancelled. Run `flint setup` to configure a provider.");
                eprintln!("  Or set credentials in: {}", env_path.display());
                return Ok(());
            }
            provider::load_env_override(&env_path);
            let new_type = std::env::var("FLINT_PROVIDER").unwrap_or_else(|_| provider_type.clone());
            let new_model = std::env::var("FLINT_MODEL").unwrap_or_else(|_| model.clone());
            provider::build_provider(&new_type, &new_model)?
        }
    };

    // Wrap with retry logic for transient API errors
    let prov: Box<dyn Provider> = Box::new(flint_provider::RetryProvider::new(raw_prov));

    config.provider.r#type = provider_type;
    config.provider.model = model;

    let base_system: String = args
        .system
        .clone()
        .or_else(|| config.agent.system_prompt.clone())
        .unwrap_or_else(|| prompt::DEFAULT_SYSTEM.to_string());

    let mut system = prompt::build_system_prompt(&base_system, &config, working_dir);

    // If running as a sub-agent, inject task completion instructions
    if args.spawn_context.is_some() {
        config.features.memory.auto_extract = false;
        config.features.compaction.enabled = false;
        system.push_str("\n\n## Task Completion\n\
            You are a sub-agent. After completing your task, \
            output your full result as text and end with `[TASK_COMPLETE]` on a new line. \
            Do NOT write files unless explicitly asked. The coordinator receives your text directly.\n\n\
            ## Tool Usage\n\
            Always provide ALL required parameters:\n\
            - `read`: requires `path`\n\
            - `write`: requires `path` AND `content`\n\
            - `edit`: requires `path`, `old_string`, AND `new_string`\n\
            - `bash`: requires `command`");
    }

    let mut registry = ToolRegistry::new();
    let checkpoint_store = flint_agent::checkpoint::new_store();
    let turn_counter = Arc::new(std::sync::atomic::AtomicU32::new(0));
    tools::register_builtins(&mut registry, checkpoint_store.clone(), turn_counter.clone());

    // Auto-poke hint in system prompt (only for main agents, not sub-agents)
    if args.spawn_context.is_none() {
        system.push_str("\n\n## Todo Tool\n\
            For multi-step requests, you MUST use the `todo` tool first:\n\
            1. `todo add` each sub-task before starting work\n\
            2. Execute them one by one\n\
            3. `todo update` each to `completed` when done\n\n\
            Simple single-step tasks (one read, one write, one question) do not need todos.\n\
            After each turn with incomplete todos, you will receive an automatic \
            \"continue working\" prompt — keep going until all are done.");
    }

    // Initialize memory system (if enabled)
    let memory: Option<Arc<Mutex<flint_memory::MemoryManager>>> =
        if config.features.is_enabled(Feature::Memory) {
            let mem_config = flint_memory::MemoryConfig {
                max_core_blocks: config.features.memory.max_core_blocks,
                max_block_chars: config.features.memory.max_block_chars,
                auto_extract: config.features.memory.auto_extract,
                search_limit: config.features.memory.search_limit,
                ..Default::default()
            };
            match flint_memory::MemoryManager::new(mem_config, Some(working_dir)) {
                Ok(mm) => {
                    // Inject core memory into system prompt
                    system = prompt::append_core_memory(&system, mm.core_blocks());
                    let shared = Arc::new(Mutex::new(mm));
                    tools::register_memory_tools(&mut registry, shared.clone());
                    eprintln!("Memory: enabled (core + archival)");
                    Some(shared)
                }
                Err(e) => {
                    eprintln!("Memory: failed to initialize: {}", e);
                    None
                }
            }
        } else {
            None
        };

    // Initialize todo system and auto-poke (main agent only, not sub-agents)
    let todo_store = flint_agent::todo::new_store();
    let auto_poke = if args.spawn_context.is_none() {
        tools::register_todo_tool(&mut registry, todo_store.clone());
        Some(crate::repl::auto_poke::AutoPoke::new(todo_store))
    } else {
        None
    };

    // Connect MCP servers (only enabled ones)
    let enabled_mcp: std::collections::HashMap<_, _> = config.mcp_servers.iter()
        .filter(|(_, cfg)| cfg.enabled)
        .map(|(k, v)| (k.clone(), v.clone()))
        .collect();
    let mut mcp_manager = McpManager::new();
    if !enabled_mcp.is_empty() {
        eprintln!("Connecting to {} MCP server(s)...", enabled_mcp.len());
        match mcp_manager.connect_all(&enabled_mcp).await {
            Ok(mcp_tools) => {
                let count = mcp_tools.len();
                for tool in mcp_tools {
                    registry.register(tool);
                }
                if count > 0 {
                    eprintln!("MCP: {} tools registered", count);
                }
            }
            Err(e) => eprintln!("MCP error: {}", e),
        }
    }

    let ctx = ToolContext {
        working_dir: working_dir.to_path_buf(),
    };

    // Ctrl+C handler
    let cancel = Arc::new(AtomicBool::new(false));
    {
        let cancel = cancel.clone();
        let _ = ctrlc::set_handler(move || {
            cancel.store(true, Ordering::Relaxed);
        });
    }

    // Convert Provider to Arc for sharing with swarm sub-agents
    let prov_arc: Arc<dyn Provider> = Arc::from(prov);

    // Initialize swarm system (if enabled)
    let (swarm, swarm_notify): (Option<Arc<Mutex<flint_swarm::SwarmManager>>>, _) =
        if config.features.is_enabled(Feature::Swarm) {
            let swarm_config = flint_swarm::SwarmConfig {
                max_agents: config.features.swarm.max_agents,
                agent_max_turns: config.features.swarm.agent_max_turns,
                max_output_chars: config.agent.max_output_chars,
                open_viewer: true,
            };
            let (output_tx, output_rx) = flint_swarm::output::channel();
            tokio::spawn(flint_swarm::output::display_loop(output_rx));

            let router = match flint_swarm::MessageRouter::start().await {
                Ok(r) => {
                    eprintln!("Router: listening on {}", r.addr);
                    Some(Arc::new(r))
                }
                Err(e) => {
                    eprintln!("Router: failed to start: {}", e);
                    None
                }
            };

            // Build a separate provider for sub-agents if swarm model is configured
            let sub_agent_prov: Arc<dyn Provider> =
                if let Some(ref swarm_model) = config.features.swarm.model {
                    match provider::build_provider(&config.provider.r#type, swarm_model) {
                        Ok(p) => Arc::from(p),
                        Err(e) => {
                            eprintln!("Warning: failed to build swarm model provider ({}), falling back to main model", e);
                            prov_arc.clone()
                        }
                    }
                } else {
                    prov_arc.clone()
                };

            let sub_agent_registry = registry.clone();
            let mut manager = flint_swarm::SwarmManager::new(
                swarm_config,
                sub_agent_prov,
                working_dir.to_path_buf(),
                system.clone(),
                output_tx,
                sub_agent_registry,
                router.clone(),
            );
            let notify_rx = manager.take_notify_rx();
            let shared = Arc::new(Mutex::new(manager));
            let model_selection = &config.features.swarm.model_selection;
            let slot_info = if model_selection == "slots" && !config.features.swarm.agents.is_empty() {
                let slot_list: Vec<String> = config.features.swarm.agents.iter().enumerate()
                    .map(|(i, p)| {
                        if p.model.is_empty() { format!("slot={}: (default)", i + 1) }
                        else { format!("slot={}: {}", i + 1, p.model) }
                    })
                    .collect();
                format!("\n\n**Model selection: slots** (auto-assigned round-robin)\n\
                    Configured slots:\n{}\n\
                    - The `model=` parameter is IGNORED in slots mode.\n\
                    - To target a specific slot, use `slot=N` (e.g. `slot=1`).\n\
                    - Without `slot=`, agents are assigned slots automatically in order.",
                    slot_list.iter().map(|s| format!("  - {}", s)).collect::<Vec<_>>().join("\n"))
            } else if model_selection == "fixed" {
                let fixed_model = config.features.swarm.model.as_deref().unwrap_or("default");
                format!("\n\n**Model selection: fixed** → all agents use `{}`", fixed_model)
            } else {
                "\n\n**Model selection: auto** — use `model=` to override per-agent.".to_string()
            };
            system = format!(
                "{}\n\n## Swarm Mode\n\
                You have access to sub-agents via the `swarm` tool.\n\n\
                **How to use:**\n\
                - `swarm spawn prompt=\"task\"` — spawns a sub-agent.\n\
                - For parallel work, call multiple `swarm spawn` in ONE message.\n\
                - Sub-agent results are delivered AUTOMATICALLY when they complete.\n\
                - Do NOT use swarm wait — results arrive as system messages.\n\
                - After spawning, respond to the user immediately. Results will appear later.\n\
                {}",
                system, slot_info
            );
            // Build agent models list and provider factory for SwarmTool
            let agent_models: Vec<String> = config.features.swarm.agents.iter()
                .map(|p| p.model.clone())
                .collect();
            let swarm_provider_type = config.provider.r#type.clone();
            let build_provider: flint_swarm::ProviderFactory = Box::new(move |model: &str| {
                provider::build_provider(&swarm_provider_type, model)
                    .ok()
                    .map(|p| Arc::from(p) as Arc<dyn Provider>)
            });

            flint_swarm::register_swarm_tools(
                &mut registry,
                shared.clone(),
                router.clone(),
                config.features.swarm.spawn_mode.clone(),
                config.features.swarm.model.clone(),
                agent_models,
                build_provider,
                config.features.swarm.model_selection.clone(),
            );
            eprintln!("Swarm: enabled (max {} agents)", config.features.swarm.max_agents);
            (Some(shared), notify_rx)
        } else {
            (None, None)
        };

    if let Some(prompt) = &args.prompt {
        // One-shot mode
        let mut session = Session::new();
        session.add_user(prompt);
        let render_line = |line: &str| {
            crate::repl::render::render_markdown_line_to_stdout(line);
        };
        if let Err(e) = flint_agent::run_turn(
            prov_arc.as_ref(),
            &mut session,
            &registry,
            &system,
            &ctx,
            config.agent.max_turns,
            Some(cancel),
            config.agent.max_output_chars,
            false,
            None,
            Some(&render_line),
        )
        .await
        {
            eprintln!("\n! Error: {}", e);
            eprintln!("  Run 'flint setup' to reconfigure provider.\n");
            std::process::exit(1);
        }
    } else {
        // REPL mode — inject conversation history from spawn context if available
        let mut repl_session = Session::new();
        if let Some(ref ctx_path) = args.spawn_context {
            if let Ok(content) = std::fs::read_to_string(ctx_path) {
                if let Ok(ctx) = serde_json::from_str::<flint_swarm::SpawnContext>(&content) {
                    if let Some(ref history) = ctx.conversation_history {
                        for msg in history {
                            repl_session.messages.push(msg.clone());
                        }
                    }
                }
            }
        }
        repl::run(
            config,
            prov_arc,
            repl_session,
            registry,
            &system,
            &ctx,
            cancel,
            mcp_manager,
            working_dir,
            memory,
            swarm,
            swarm_notify,
            auto_poke,
            checkpoint_store,
            turn_counter,
            args.initial_message.clone(),
            args.message_file.clone(),
            args.router_addr.clone(),
            args.agent_id.clone(),
        )
        .await?;
    }

    Ok(())
}

// ── Main ──────────────────────────────────────────────────────────────────

#[tokio::main]
async fn main() -> Result<()> {
    let mut cli = Cli::parse();
    let working_dir = dunce::canonicalize(&cli.dir)?;
    let mut spawn_model: Option<String> = None;

    // --system-file: read system prompt from file
    if let Some(ref path) = cli.system_file {
        cli.system = Some(std::fs::read_to_string(path)
            .map_err(|e| anyhow::anyhow!("failed to read system file '{}': {}", path, e))?);
    }

    // --initial-message-file: read initial message from file
    if let Some(ref path) = cli.initial_message_file {
        cli.initial_message = Some(std::fs::read_to_string(path)
            .map_err(|e| anyhow::anyhow!("failed to read initial message file '{}': {}", path, e))?);
    }

    // Sub-agent mode: load SpawnContext and override CLI fields
    if let Some(ref ctx_path) = cli.spawn_context {
        let content = std::fs::read_to_string(ctx_path)
            .map_err(|e| anyhow::anyhow!("failed to read spawn context '{}': {}", ctx_path, e))?;
        let ctx: flint_swarm::SpawnContext = serde_json::from_str(&content)
            .map_err(|e| anyhow::anyhow!("invalid spawn context JSON: {}", e))?;
        cli.router_addr = Some(ctx.router_addr.clone());
        cli.agent_id = Some(ctx.agent_id.clone());
        cli.system = Some(ctx.system_prompt.clone());
        cli.initial_message = Some(ctx.initial_prompt.clone());
        // Store spawn context model for later use in AgentArgs
        spawn_model = ctx.model.clone();
        std::env::set_var("FLINT_SUB_AGENT_ID", &ctx.agent_id);
        std::env::set_var("FLINT_SUB_TASK_ID", &ctx.task_id);
        std::env::set_var("FLINT_SUB_ROUTER_ADDR", &ctx.router_addr);
    }

    #[cfg(target_os = "windows")]
    {
        let _ = enable_ansi_support::enable_ansi_support();
    }

    init_tracing("warn");

    // Display client mode
    if cli.display {
        let addr = cli.router_addr.as_deref()
            .ok_or_else(|| anyhow::anyhow!("--display requires --router-addr"))?;
        let aid = cli.agent_id.as_deref()
            .ok_or_else(|| anyhow::anyhow!("--display requires --agent-id"))?;
        return repl::run_display_mode(addr, aid).await;
    }

    match cli.command {
        Some(Commands::Config) => cmd_config(&working_dir),
        Some(Commands::Setup(args)) => cmd_setup(args, &working_dir),
        Some(Commands::Agent(mut args)) => {
            if args.model.is_none() {
                args.model = spawn_model;
            }
            cmd_agent(args, &working_dir).await
        }
        None => {
            cmd_agent(
                AgentArgs {
                    prompt: cli.prompt,
                    provider: None,
                    model: spawn_model,
                    system: cli.system,
                    initial_message: cli.initial_message,
                    message_file: cli.message_file,
                    router_addr: cli.router_addr,
                    agent_id: cli.agent_id,
                    spawn_context: cli.spawn_context,
                },
                &working_dir,
            )
            .await
        }
    }
}

fn init_tracing(level: &str) {
    use tracing::Level;
    let level = match level {
        "trace" => Level::TRACE,
        "debug" => Level::DEBUG,
        "info" => Level::INFO,
        "warn" => Level::WARN,
        "error" => Level::ERROR,
        _ => Level::WARN,
    };
    tracing_subscriber::fmt()
        .with_env_filter(
            tracing_subscriber::EnvFilter::from_default_env().add_directive(level.into()),
        )
        .init();
}
