//! flint — Easy-to-hack agent harness in Rust.

mod cli;
mod config_ui;
mod display;
mod input;
mod markdown;
mod model_ui;
mod prompt;
mod provider;
mod repl;
mod resume_ui;
pub mod session_import;
mod setup_ui;
mod tools;

use anyhow::Result;
use clap::Parser;
use cli::{AgentArgs, Cli, Commands, SetupArgs};
use flint_agent::{Session, ToolContext, ToolRegistry};
use flint_mcp::McpManager;
use flint_provider::Provider;
use std::sync::atomic::{AtomicBool, Ordering};
use std::sync::Arc;

// ── Subcommand handlers ───────────────────────────────────────────────────

fn cmd_config(working_dir: &std::path::Path) -> Result<()> {
    let config = flint_config::load(Some(working_dir))?;
    let save_path = config.save_path(Some(working_dir));
    config_ui::run(config, &save_path)?;
    Ok(())
}

fn cmd_setup(args: SetupArgs, working_dir: &std::path::Path) -> Result<()> {
    let env_path = provider::resolve_env_path(working_dir);

    if let (Some(provider), Some(key)) = (&args.provider, &args.key) {
        return setup_auto(&env_path, provider, key, args.base_url.as_deref(), args.model.as_deref());
    }

    let configured = setup_ui::run(&env_path)?;
    if configured {
        print_post_setup_guidance(&env_path);
    }
    Ok(())
}

fn setup_auto(
    env_path: &std::path::Path,
    provider: &str,
    api_key: &str,
    base_url: Option<&str>,
    model: Option<&str>,
) -> Result<()> {
    let p = setup_ui::find_provider(provider).ok_or_else(|| {
        anyhow::anyhow!("unknown provider '{}'. Supported: openai, anthropic", provider)
    })?;

    let mut lines = vec![
        "# flint configuration -- generated by `flint setup`".to_string(),
        format!("FLINT_PROVIDER={}", p.name),
        format!("{}={}", p.env_key, api_key),
    ];

    if let Some(url) = base_url {
        lines.push(format!("{}={}", p.env_base, url));
    }
    if let Some(m) = model {
        lines.push(format!("{}={}", p.env_model, m));
    }

    let content = if env_path.exists() {
        let existing = std::fs::read_to_string(env_path)?;
        let filtered: String = existing
            .lines()
            .filter(|line| {
                !line.starts_with(&format!("{}=", p.env_key))
                    && !line.starts_with(&format!("{}=", p.env_base))
                    && !line.starts_with(&format!("{}=", p.env_model))
                    && !line.starts_with("FLINT_PROVIDER=")
                    && !line.starts_with("FLINT_MODEL=")
            })
            .collect::<Vec<_>>()
            .join("\n");
        format!("{}\n{}\n", filtered.trim_end(), lines.join("\n"))
    } else {
        format!("{}\n", lines.join("\n"))
    };

    std::fs::write(env_path, &content)?;

    println!("+ Provider configured:");
    println!("  Provider : {}", p.label);
    println!(
        "  API Key  : {}...{}",
        &api_key[..4.min(api_key.len())],
        &api_key[api_key.len().saturating_sub(4)..]
    );
    if let Some(url) = base_url {
        println!("  Base URL : {}", url);
    }
    if let Some(m) = model {
        println!("  Model    : {}", m);
    }
    println!("  Saved to : {}", env_path.display());
    print_post_setup_guidance(env_path);
    Ok(())
}

fn print_post_setup_guidance(env_path: &std::path::Path) {
    println!();
    println!("Next steps:");
    println!("  - Run `flint` to start the interactive REPL");
    println!("  - Run `flint \"your prompt\"` for a one-shot query");
    println!("  - Run `flint config` to adjust features and settings");
    println!("  - Edit {} to change credentials", env_path.display());
    println!();
}

// ── Agent command ─────────────────────────────────────────────────────────

async fn cmd_agent(args: AgentArgs, working_dir: &std::path::Path) -> Result<()> {
    // Load .env: global -> project -> cwd
    let global_env = provider::home_dir().map(|h| h.join(".flint").join(".env"));
    let project_env = working_dir.join(".env");
    let cwd_env = std::env::current_dir().ok().map(|d| d.join(".env"));

    if let Some(ref path) = global_env {
        if path.exists() {
            provider::load_env_override(path);
        }
    }
    if project_env.exists() {
        provider::load_env_override(&project_env);
    }
    if let Some(ref path) = cwd_env {
        if path.exists() && path.as_path() != project_env.as_path() {
            provider::load_env_override(path);
        }
    }

    let env_path = provider::resolve_env_path(working_dir);
    let mut config = flint_config::load(Some(working_dir))?;

    // Resolve provider: CLI > env > config
    let env_provider = std::env::var("FLINT_PROVIDER").ok();
    let env_model = std::env::var("FLINT_MODEL").ok();

    let provider_type = args
        .provider
        .clone()
        .or_else(|| env_provider.clone())
        .unwrap_or_else(|| config.provider.r#type.clone());
    let model = args
        .model
        .clone()
        .or_else(|| env_model.clone())
        .unwrap_or_else(|| config.provider.model.clone());

    // Build provider; on failure, launch setup wizard
    let prov: Box<dyn Provider> = match provider::build_provider(&provider_type, &model) {
        Ok(p) => p,
        Err(e) => {
            eprintln!("{}\n", e);
            eprintln!("Launching setup wizard...\n");
            let configured = setup_ui::run(&env_path)?;
            if !configured {
                eprintln!("Setup cancelled. Run `flint setup` to configure a provider.");
                eprintln!("  Or set credentials in: {}", env_path.display());
                return Ok(());
            }
            provider::load_env_override(&env_path);
            let new_type = std::env::var("FLINT_PROVIDER").unwrap_or_else(|_| provider_type.clone());
            let new_model = std::env::var("FLINT_MODEL").unwrap_or_else(|_| model.clone());
            provider::build_provider(&new_type, &new_model)?
        }
    };

    config.provider.r#type = provider_type;
    config.provider.model = model;

    let base_system: String = args
        .system
        .clone()
        .or_else(|| config.agent.system_prompt.clone())
        .unwrap_or_else(|| prompt::DEFAULT_SYSTEM.to_string());

    let system = prompt::build_system_prompt(&base_system, &config, working_dir);

    let mut registry = ToolRegistry::new();
    tools::register_builtins(&mut registry);

    // Connect MCP servers
    let mut mcp_manager = McpManager::new();
    if !config.mcp_servers.is_empty() {
        eprintln!("Connecting to {} MCP server(s)...", config.mcp_servers.len());
        match mcp_manager.connect_all(&config.mcp_servers).await {
            Ok(mcp_tools) => {
                let count = mcp_tools.len();
                for tool in mcp_tools {
                    registry.register(tool);
                }
                if count > 0 {
                    eprintln!("MCP: {} tools registered", count);
                }
            }
            Err(e) => eprintln!("MCP error: {}", e),
        }
    }

    let ctx = ToolContext {
        working_dir: working_dir.to_path_buf(),
    };

    // Ctrl+C handler
    let cancel = Arc::new(AtomicBool::new(false));
    {
        let cancel = cancel.clone();
        let _ = ctrlc::set_handler(move || {
            cancel.store(true, Ordering::Relaxed);
        });
    }

    if let Some(prompt) = &args.prompt {
        // One-shot mode
        let mut session = Session::new();
        session.add_user(prompt);
        if let Err(e) = flint_agent::run_turn(
            prov.as_ref(),
            &mut session,
            &registry,
            &system,
            &ctx,
            config.agent.max_turns,
            Some(cancel),
        )
        .await
        {
            eprintln!("\n! Error: {}", e);
            eprintln!("  Run 'flint setup' to reconfigure provider.\n");
            std::process::exit(1);
        }
    } else {
        // REPL mode
        repl::run(
            config,
            prov,
            Session::new(),
            &registry,
            &system,
            &ctx,
            cancel,
            mcp_manager,
            working_dir,
        )
        .await?;
    }

    Ok(())
}

// ── Main ──────────────────────────────────────────────────────────────────

#[tokio::main]
async fn main() -> Result<()> {
    let cli = Cli::parse();
    let working_dir = dunce::canonicalize(&cli.dir)?;

    #[cfg(target_os = "windows")]
    {
        let _ = enable_ansi_support::enable_ansi_support();
    }

    init_tracing("warn");

    match cli.command {
        Some(Commands::Config) => cmd_config(&working_dir),
        Some(Commands::Setup(args)) => cmd_setup(args, &working_dir),
        Some(Commands::Agent(args)) => cmd_agent(args, &working_dir).await,
        None => {
            cmd_agent(
                AgentArgs {
                    prompt: cli.prompt,
                    provider: None,
                    model: None,
                    system: None,
                },
                &working_dir,
            )
            .await
        }
    }
}

fn init_tracing(level: &str) {
    use tracing::Level;
    let level = match level {
        "trace" => Level::TRACE,
        "debug" => Level::DEBUG,
        "info" => Level::INFO,
        "warn" => Level::WARN,
        "error" => Level::ERROR,
        _ => Level::WARN,
    };
    tracing_subscriber::fmt()
        .with_env_filter(
            tracing_subscriber::EnvFilter::from_default_env().add_directive(level.into()),
        )
        .init();
}
